import { OnlineStatusProvider } from "@/hooks/useOnlineStatus";
import Head from "next/head";

interface Props {
  children: React.ReactNode;
}

function Layout({ children }: Props): JSX.Element {
  return (
    <OnlineStatusProvider>
      <Head>
        <title>Music Raider</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="raider">{children}</div>
    </OnlineStatusProvider>
  );
}

export default Layout;
