import Head from "next/head";
import { Header, VisualizationArea } from "@/components";
import { SharedChosenResultsProvider } from "@/containers";

function Home() {
  return (
    <>
      <Head>
        <title>Music Raider</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SharedChosenResultsProvider>
        <Header />

        <main className="main">
          <VisualizationArea />
        </main>
      </SharedChosenResultsProvider>
    </>
  );
}

export default Home;
