import Head from "next/head";
import { Header } from "@/components";

function Home() {
  return (
    <>
      <Head>
        <title>Music Raider</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="main">main content</main>
    </>
  );
}

export default Home;
